---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myresultvar

  - name: debug myresultvar
    debug:
      msg: "{{myresultvar}}"

  - name: i want to install git
    apt:
      name: git
      state: present
    when: myresultvar.stderr==""
  
  - name: i want to install tree
    apt:
       name: tree
       state: present
    when: myresultvar.stderr!=""
      