---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f
    register: myresultvar

  - name: debug myresultvar
    debug:
      msg: "{{myresultvar}}"