---
- hosts: all
  tasks: 
  - name: i want to ping all nodes
    ping:

  - name: i want to install tree
    apt:
      name: tree
      state: present 

  - name: i want to install wget
    apt:
      name: wget
      state: present
      