---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - include_tasks: myfile.yml
  
  - name: i want to install webserver
    apt:
      name: apache2
      state: present

  - name: restart webserver
    service:
      name: apache2
      state: restarted

  - name: copy myindex file into ansible node side
    template:
       src: myindexfile.j2
       dest: /var/www/html/index.html