---
- hosts: 172.31.18.165
  become: yes
  tasks:
  - name: install git,treeaaa and wget ............etc
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - tree
      - wget