---
# tasks file for mytom8onU16role
- include_tasks: installjava.yml
- include_tasks: createUserGroup.yml
- include_tasks: installtomcat.yml
- include_tasks: Permissions.yml
- include_tasks: tomservicefile.yml
- include_tasks: starttomcat.yml
